#!/bin/bash
cd Test/
counter=1
for((i=1;i<3000;i++))
do 
	mkdir $i.dr # создание папки
	cp lb1.odt lb1-copy.odt
	mv lb1-copy.odt $i.dr
	> $i # создание файла
	ls -l ~ >> $i
	#вывод размера директории
	du -sh ~/Test
done
for((i=3000-1; i > 1; i--))
do
	cd $i.dr
	rm lb1-copy.odt
	cd ..
	rmdir $i.dr #удаление папок
	rm $i #удаление файлов
done

